// Generated by scripts/generate-trusted-catalog.mjs from catalog/trusted-resources.json.
// Source SHA256: 7218e04e157860120b1cc1a1f64c245b56753979b238001dac8d6369f02863e2. Do not edit by hand.

export type GeneratedTrustedResourceMetadata = {
  catalogStatus: "active" | "deprecated" | "revoked";
  statusReason?: string;
  replacedBy?: string;
  verification: {
    checksumAlgorithm: "sha256";
    checksumSource: "vendor-manifest" | "github-release-asset-digest" | "pinned-repository-snapshot";
    checksumSourceUrl: string;
    signatureType: "authenticode" | "upstream-release" | "none";
    expectedPublisher?: string;
    signatureEnforcement: "required" | "checksum-only" | "not-applicable";
  };
  download: {
    url: string;
    expectedSha256: string;
    maxSizeMb: number;
    allowedHosts: string[];
  };
};

export const trustedCatalogMetadata = {
  "schemaVersion": 1,
  "catalogVersion": "2026.07.26.2",
  "generatedAt": "2026-07-25T16:00:00.000Z",
  "expiresAt": "2027-01-25T16:00:00.000Z",
  "sourceSha256": "7218e04e157860120b1cc1a1f64c245b56753979b238001dac8d6369f02863e2"
};

export const trustedResources: Record<string, GeneratedTrustedResourceMetadata> = {
  "python-312": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "vendor-manifest",
      "checksumSourceUrl": "https://github.com/microsoft/winget-pkgs/blob/master/manifests/p/Python/Python/3/12/3.12.10/Python.Python.3.12.installer.yaml",
      "signatureType": "authenticode",
      "expectedPublisher": "Python Software Foundation",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://www.python.org/ftp/python/3.12.10/python-3.12.10-amd64.exe",
      "expectedSha256": "67b5635e80ea51072b87941312d00ec8927c4db9ba18938f7ad2d27b328b95fb",
      "maxSizeMb": 32,
      "allowedHosts": [
        "www.python.org"
      ]
    }
  },
  "vscode": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "vendor-manifest",
      "checksumSourceUrl": "https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VisualStudioCode/1.129.0/Microsoft.VisualStudioCode.installer.yaml",
      "signatureType": "authenticode",
      "expectedPublisher": "Microsoft Corporation",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://vscode.download.prss.microsoft.com/dbazure/download/stable/125df4672b8a6a34975303c6b0baa124e560a4f7/VSCodeUserSetup-x64-1.129.0.exe",
      "expectedSha256": "46b5a269597ddffa1a349212074b4ef12c9edbad6a69c193c10b1794a1a53582",
      "maxSizeMb": 160,
      "allowedHosts": [
        "vscode.download.prss.microsoft.com"
      ]
    }
  },
  "git": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "github-release-asset-digest",
      "checksumSourceUrl": "https://api.github.com/repos/git-for-windows/git/releases/tags/v2.55.0.windows.3",
      "signatureType": "authenticode",
      "expectedPublisher": "Open Source Developer, Johannes Schindelin",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://github.com/git-for-windows/git/releases/download/v2.55.0.windows.3/Git-2.55.0.3-64-bit.exe",
      "expectedSha256": "af12577d0fdff74243a5988197aa49b957d5044edc17004f6ddf0768996f1dca",
      "maxSizeMb": 80,
      "allowedHosts": [
        "github.com",
        "release-assets.githubusercontent.com"
      ]
    }
  },
  "node-lts": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "vendor-manifest",
      "checksumSourceUrl": "https://nodejs.org/dist/v24.18.0/SHASUMS256.txt",
      "signatureType": "upstream-release",
      "expectedPublisher": "Node.js Release Team",
      "signatureEnforcement": "checksum-only"
    },
    "download": {
      "url": "https://nodejs.org/dist/v24.18.0/node-v24.18.0-x64.msi",
      "expectedSha256": "e30cd4ca15529583afe0efc978f1ae3ab3a93c2400c222d0752d17900552ebb3",
      "maxSizeMb": 48,
      "allowedHosts": [
        "nodejs.org"
      ]
    }
  },
  "powershell-7": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "github-release-asset-digest",
      "checksumSourceUrl": "https://api.github.com/repos/PowerShell/PowerShell/releases/tags/v7.6.4",
      "signatureType": "authenticode",
      "expectedPublisher": "Microsoft Corporation",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://github.com/PowerShell/PowerShell/releases/download/v7.6.4/PowerShell-7.6.4-win-x64.msi",
      "expectedSha256": "d11942df52fd12470169797abfa4781d9480efdc81000ba4fa55a5b921ed8dd0",
      "maxSizeMb": 128,
      "allowedHosts": [
        "github.com",
        "release-assets.githubusercontent.com"
      ]
    }
  },
  "sample-project": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "pinned-repository-snapshot",
      "checksumSourceUrl": "https://github.com/yogurt-stack/XL-Agent/commit/dc711ec575b9a22da51fda01c1c2952aceb3f261",
      "signatureType": "none",
      "signatureEnforcement": "not-applicable"
    },
    "download": {
      "url": "https://codeload.github.com/yogurt-stack/XL-Agent/zip/dc711ec575b9a22da51fda01c1c2952aceb3f261",
      "expectedSha256": "1faaf2615901364045d223d8c7fc63ea2996b801dea194d50468c98558383353",
      "maxSizeMb": 4,
      "allowedHosts": [
        "codeload.github.com"
      ]
    }
  },
  "miniforge-py312": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "github-release-asset-digest",
      "checksumSourceUrl": "https://api.github.com/repos/conda-forge/miniforge/releases/tags/26.3.2-3",
      "signatureType": "authenticode",
      "expectedPublisher": "conda-forge",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://github.com/conda-forge/miniforge/releases/download/26.3.2-3/Miniforge3-26.3.2-3-Windows-x86_64.exe",
      "expectedSha256": "14a8635465b5190537ddad6286746ffebbc55a1ed2a7bb14a506595fe3191e1e",
      "maxSizeMb": 96,
      "allowedHosts": [
        "github.com",
        "release-assets.githubusercontent.com"
      ]
    }
  },
  "vscode-machine": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "vendor-manifest",
      "checksumSourceUrl": "https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VisualStudioCode/1.129.0/Microsoft.VisualStudioCode.installer.yaml",
      "signatureType": "authenticode",
      "expectedPublisher": "Microsoft Corporation",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://vscode.download.prss.microsoft.com/dbazure/download/stable/125df4672b8a6a34975303c6b0baa124e560a4f7/VSCodeSetup-x64-1.129.0.exe",
      "expectedSha256": "92928c03031740352816c0c7feeeafa0b065a59d70ba07a7793b5e9c28beffcf",
      "maxSizeMb": 160,
      "allowedHosts": [
        "vscode.download.prss.microsoft.com"
      ]
    }
  },
  "git-portable": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "github-release-asset-digest",
      "checksumSourceUrl": "https://api.github.com/repos/git-for-windows/git/releases/tags/v2.55.0.windows.3",
      "signatureType": "authenticode",
      "expectedPublisher": "Open Source Developer, Johannes Schindelin",
      "signatureEnforcement": "required"
    },
    "download": {
      "url": "https://github.com/git-for-windows/git/releases/download/v2.55.0.windows.3/PortableGit-2.55.0.3-64-bit.7z.exe",
      "expectedSha256": "ab00566336b5472120f9a52d34f2e79c5406535792acb0548001ffd0bd090e5d",
      "maxSizeMb": 80,
      "allowedHosts": [
        "github.com",
        "release-assets.githubusercontent.com"
      ]
    }
  },
  "node-lts-zip": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "vendor-manifest",
      "checksumSourceUrl": "https://nodejs.org/dist/v24.18.0/SHASUMS256.txt",
      "signatureType": "upstream-release",
      "expectedPublisher": "Node.js Release Team",
      "signatureEnforcement": "checksum-only"
    },
    "download": {
      "url": "https://nodejs.org/dist/v24.18.0/node-v24.18.0-win-x64.zip",
      "expectedSha256": "0ae68406b42d7725661da979b1403ec9926da205c6770827f33aac9d8f26e821",
      "maxSizeMb": 48,
      "allowedHosts": [
        "nodejs.org"
      ]
    }
  },
  "powershell-7-zip": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "github-release-asset-digest",
      "checksumSourceUrl": "https://api.github.com/repos/PowerShell/PowerShell/releases/tags/v7.6.4",
      "signatureType": "upstream-release",
      "expectedPublisher": "Microsoft Corporation",
      "signatureEnforcement": "checksum-only"
    },
    "download": {
      "url": "https://github.com/PowerShell/PowerShell/releases/download/v7.6.4/PowerShell-7.6.4-win-x64.zip",
      "expectedSha256": "80832551c52809301e6071c8bac977beb5a2f1ec953eb4db9f94deb953333793",
      "maxSizeMb": 128,
      "allowedHosts": [
        "github.com",
        "release-assets.githubusercontent.com"
      ]
    }
  },
  "sample-project-mirror": {
    "catalogStatus": "active",
    "verification": {
      "checksumAlgorithm": "sha256",
      "checksumSource": "pinned-repository-snapshot",
      "checksumSourceUrl": "https://github.com/yogurt-stack/XL-Agent/commit/dc711ec575b9a22da51fda01c1c2952aceb3f261",
      "signatureType": "none",
      "signatureEnforcement": "not-applicable"
    },
    "download": {
      "url": "https://github.com/yogurt-stack/XL-Agent/archive/dc711ec575b9a22da51fda01c1c2952aceb3f261.zip",
      "expectedSha256": "1faaf2615901364045d223d8c7fc63ea2996b801dea194d50468c98558383353",
      "maxSizeMb": 4,
      "allowedHosts": [
        "github.com",
        "codeload.github.com"
      ]
    }
  }
};
